version: "2.2"
services:
  sample-service:
    build:
      context: ./sample-service
    command: npm start
    container_name: webservice-nodejs
    networks:
      - gatling_network
    volumes:
      - ./sample-service:/app
    ports:
      - "8000:8000"
  sample-service2:
    build:
      context: ./sample-service2
    working_dir: /go/src/sample-service2
    container_name: webservice-golang
    volumes:
      - "./sample-service2:/go/src/sample-service2"
    networks:
      - gatling_network
    ports:
      - "4000:4000"
  gatling-runner:
    image: gatling:2.3.0
    scale: 2 # Scale to see the result of multiple nodes
    build:
      context: gatling/2.3.0
    command: [-s, sample.SampleService]
    networks:
      - gatling_network
    depends_on:
      - grafana
    environment:
      - LOCAL_USER_ID=`id -u $USER`
    volumes:
      - ./gatling/2.3.0/simulations:/opt/app/java/gatling/user-files/simulations
      - ./gatling/2.3.0/results:/opt/app/java/gatling/results
  grafana:
    image: grafana/grafana
    networks:
      - gatling_network
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./config.ini:/etc/grafana/config.ini
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    
  influxdb:
    image: influxdb:2.3.0
    build:
      context: influxdb/1.2.0-alpine
    networks:
      - gatling_network
    volumes:
      - ./influxdb/storage:/var/lib/influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "2003:2003"
networks:
  gatling_network:
